/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'publishedDate' : Time,
  'slug' : string,
  'author' : string,
}
export interface BodySystem {
  'id' : bigint,
  'functionText' : string,
  'name' : string,
  'slug' : string,
  'description' : string,
  'neetPoints' : string,
  'commonDisorders' : string,
  'diagramUrl' : [] | [string],
  'structureText' : string,
}
export interface Contact {
  'id' : bigint,
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
}
export interface MCQ {
  'id' : bigint,
  'correctOption' : string,
  'question' : string,
  'explanation' : string,
  'systemId' : bigint,
  'optionA' : string,
  'optionB' : string,
  'optionC' : string,
  'optionD' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<
    [string, string, string, string, boolean],
    undefined
  >,
  'createBodySystem' : ActorMethod<
    [string, string, string, string, string, string, string, [] | [string]],
    undefined
  >,
  'createMCQ' : ActorMethod<
    [bigint, string, string, string, string, string, string, string],
    undefined
  >,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteBodySystem' : ActorMethod<[bigint], undefined>,
  'deleteMCQ' : ActorMethod<[bigint], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllBodySystems' : ActorMethod<[], Array<BodySystem>>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllMCQs' : ActorMethod<[], Array<MCQ>>,
  'getBodySystemsByDisorder' : ActorMethod<[], Array<BodySystem>>,
  'getBodySystemsByFunction' : ActorMethod<[], Array<BodySystem>>,
  'getBodySystemsByStructure' : ActorMethod<[], Array<BodySystem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    undefined
  >,
  'updateBodySystem' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
    ],
    undefined
  >,
  'updateMCQ' : ActorMethod<
    [bigint, bigint, string, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];