/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'publishedDate' : Time,
  'slug' : IDL.Text,
  'author' : IDL.Text,
});
export const BodySystem = IDL.Record({
  'id' : IDL.Nat,
  'functionText' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'neetPoints' : IDL.Text,
  'commonDisorders' : IDL.Text,
  'diagramUrl' : IDL.Opt(IDL.Text),
  'structureText' : IDL.Text,
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const MCQ = IDL.Record({
  'id' : IDL.Nat,
  'correctOption' : IDL.Text,
  'question' : IDL.Text,
  'explanation' : IDL.Text,
  'systemId' : IDL.Nat,
  'optionA' : IDL.Text,
  'optionB' : IDL.Text,
  'optionC' : IDL.Text,
  'optionD' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'createBodySystem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'createMCQ' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deleteBodySystem' : IDL.Func([IDL.Nat], [], []),
  'deleteMCQ' : IDL.Func([IDL.Nat], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllBodySystems' : IDL.Func([], [IDL.Vec(BodySystem)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllMCQs' : IDL.Func([], [IDL.Vec(MCQ)], ['query']),
  'getBodySystemsByDisorder' : IDL.Func([], [IDL.Vec(BodySystem)], ['query']),
  'getBodySystemsByFunction' : IDL.Func([], [IDL.Vec(BodySystem)], ['query']),
  'getBodySystemsByStructure' : IDL.Func([], [IDL.Vec(BodySystem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateBodySystem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateMCQ' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'publishedDate' : Time,
    'slug' : IDL.Text,
    'author' : IDL.Text,
  });
  const BodySystem = IDL.Record({
    'id' : IDL.Nat,
    'functionText' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'neetPoints' : IDL.Text,
    'commonDisorders' : IDL.Text,
    'diagramUrl' : IDL.Opt(IDL.Text),
    'structureText' : IDL.Text,
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const MCQ = IDL.Record({
    'id' : IDL.Nat,
    'correctOption' : IDL.Text,
    'question' : IDL.Text,
    'explanation' : IDL.Text,
    'systemId' : IDL.Nat,
    'optionA' : IDL.Text,
    'optionB' : IDL.Text,
    'optionC' : IDL.Text,
    'optionD' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'createBodySystem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'createMCQ' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deleteBodySystem' : IDL.Func([IDL.Nat], [], []),
    'deleteMCQ' : IDL.Func([IDL.Nat], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllBodySystems' : IDL.Func([], [IDL.Vec(BodySystem)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllMCQs' : IDL.Func([], [IDL.Vec(MCQ)], ['query']),
    'getBodySystemsByDisorder' : IDL.Func([], [IDL.Vec(BodySystem)], ['query']),
    'getBodySystemsByFunction' : IDL.Func([], [IDL.Vec(BodySystem)], ['query']),
    'getBodySystemsByStructure' : IDL.Func(
        [],
        [IDL.Vec(BodySystem)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateBodySystem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateMCQ' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };